version: "3.8"

services:
  spring:
    container_name: spring
    image: christu6899/spring-mall
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=spring
    networks:
      - mall-app-network
  
  mysql:
    image: mysql:8.0.22
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=spring
      - MYSQL_DATABASE=mall
      - LANG=C.UTF-8
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mall-app-network

  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    networks:
      - mall-app-network

networks:
  mall-app-network:
    name: mall-app-network
  

